version: '3.9'
services:
  postgres:
    image: postgres
    container_name: blogmark_postgresql
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
